environment: test
app_host: http://localhost:4200/

credentials:
  adminUsername: <%= ENV['FS_USERNAME'] || 'admin@gmail.com' %>
  adminPassword: <%= ENV['FS_PASSWORD'] || 'password123' %>


  agentUsername: <%= ENV['FS_USERNAME'] || 'agent@gmail.com' %>
  agentPassword: <%= ENV['FS_PASSWORD'] || 'password123' %>